server:
  host: 0.0.0.0
  port: 8080

database:
  host: ${DATABASE_HOST}
  port: 3306
  name: ${DATABASE_NAME}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}

auth:
  access_key: ${AUTH_ACCESS_KEY}
  refresh_key: ${AUTH_REFRESH_KEY}
  access_expires: 5 # minutes
  refresh_expires: 10 # minutes

redis:
  address: ${REDIS_ADDRESS}
  namespace: ${REDIS_NAMESPACE}

google:
  client_id: ${GOOGLE_CLIENT_ID}
