// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: api/bulbasaur.proto

package go_pattern

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

// BulbasaurClient is the client API for Bulbasaur service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BulbasaurClient interface {
}

type bulbasaurClient struct {
	cc grpc.ClientConnInterface
}

func NewBulbasaurClient(cc grpc.ClientConnInterface) BulbasaurClient {
	return &bulbasaurClient{cc}
}

// BulbasaurServer is the server API for Bulbasaur service.
// All implementations must embed UnimplementedBulbasaurServer
// for forward compatibility
type BulbasaurServer interface {
	mustEmbedUnimplementedBulbasaurServer()
}

// UnimplementedBulbasaurServer must be embedded to have forward compatible implementations.
type UnimplementedBulbasaurServer struct {
}

func (UnimplementedBulbasaurServer) mustEmbedUnimplementedBulbasaurServer() {}

// UnsafeBulbasaurServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BulbasaurServer will
// result in compilation errors.
type UnsafeBulbasaurServer interface {
	mustEmbedUnimplementedBulbasaurServer()
}

func RegisterBulbasaurServer(s grpc.ServiceRegistrar, srv BulbasaurServer) {
	s.RegisterService(&Bulbasaur_ServiceDesc, srv)
}

// Bulbasaur_ServiceDesc is the grpc.ServiceDesc for Bulbasaur service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bulbasaur_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go_pattern.Bulbasaur",
	HandlerType: (*BulbasaurServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/bulbasaur.proto",
}
