name: Update Submodule in Parent Repo

on:
  workflow_run:
    workflows: ["Create Tag"]
    types:
      - completed

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Git config
        run: |
          git config --global user.name "ChisTrun"
          git config --global user.email "vochitrung.pst@gmail.com"

      - name: Get the new tag
        id: get_new_tag
        run: |
          # Tải tag từ file new_tag.txt
          new_tag=$(cat new_tag.txt)
          echo "New tag: $new_tag"
          echo "::set-output name=new_tag::$new_tag"

          
      - name: Checkout submodule
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Clone parent repo
        run: git clone --recursive https://github.com/ChisTrun/SkillSharp
      - name: Update submodule in parent repo
        run: |
          cd  SkillSharp
          git checkout -b bulbasour_update_${{ steps.get_new_tag.outputs.new_tag }}
          git submodule update --remote backend/Bulbasaur
          git add backend/Bulbasaur
          git commit -m "Update module to latest commit"
          git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/ChisTrun/SkillSharp.git bulbasour_update_${{ steps.get_new_tag.outputs.new_tag }}

      - name: Create Pull Request
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"title":"Update module","head":"bulbasour_update_${{ steps.get_new_tag.outputs.new_tag }}","base":"main"}' \
          https://api.github.com/repos/yourorg/parentrepo/pulls

          
