name: Update Submodule in Parent Repo

on:
  push:
    branches:
      - main

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout submodule
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Clone parent repo
        run: git clone --recursive ${{ secrets.PARENT_REPO_URL }}

      - name: Update submodule in parent repo
        run: |
          cd  ${{ secrets.PARENT_REPO }}
          git checkout -b ${{ secrets.UPDATE_BRANCH }}
          git submodule update --remote ${{ secrets.MODULE_PATH }}
          git add ${{ secrets.MODULE_PATH }}
          git commit -m "Update module to latest commit"
          git push origin ${{ secrets.UPDATE_BRANCH }}

      - name: Create Pull Request
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"title":"Update module","head":"${{ secrets.UPDATE_BRANCH }}","base":"main"}' \
          https://api.github.com/repos/yourorg/parentrepo/pulls

          
