name: Update Submodule in Parent Repo

on:
  workflow_run:
    workflows: ["create tag"]
    types:
      - completed

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Git config
        run: |
          git config --global user.name "ChisTrun"
          git config --global user.email "vochitrung.pst@gmail.com"
          
      - name: Checkout submodule
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $TAG"
          echo "::set-output name=tag::$TAG"

      - name: Clone parent repo
        run: git clone --recursive https://github.com/ChisTrun/SkillSharp

      - name: Update submodule in parent repo
        run: |
          cd SkillSharp
          TAG="${{ steps.get_tag.outputs.tag }}"
          BRANCH_NAME="bulbasour_update_${TAG}"
          git checkout -b $BRANCH_NAME
          git submodule update --remote backend/Bulbasaur
          git add backend/Bulbasaur
          git commit -m "Update module to latest commit"
          git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/ChisTrun/SkillSharp.git $BRANCH_NAME

      - name: Create Pull Request
        run: |
          TAG= "${{ steps.get_tag.outputs.tag}}"
          BRANCH_NAME="bulbasour_update_${TAG}"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"title\":\"Update module\",\"head\":\"${BRANCH_NAME}\",\"base\":\"main\"}" \
          https://api.github.com/repos/yourorg/parentrepo/pulls
